services:
  db:
    image: mysql:8.3.0
    environment:
      - 'MYSQL_DATABASE=taxi_service'
      - 'MYSQL_PASSWORD=password123'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=gwk'
      - 'TZ=Asia/Seoul'
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    command: [ "mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_general_ci" ]
volumes:
  db:
